# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HariprakashSundaram/locust-argocd
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: locust
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
