# deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.24.1
        command: ["locust"]
        args:
          - "--worker"
          - "--master-host=locust-master.locust.svc.cluster.local"
          - "--master-port=5557"
          - "--locustfile=/mnt/locust/locustfile.py"
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
        env:
          - name: LOCUST_LOCUSTFILE
            value: /mnt/locust/locustfile.py
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
