# deployment-master.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.24.1
        command: ["locust"]
        args:
          - "--master"
          - "--locustfile=/mnt/locust/locustfile.py"
        ports:
          - name: web
            containerPort: 8089
          - name: worker
            containerPort: 5557
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
          - name: reports
            mountPath: /reports
        env:
          - name: LOCUST_LOCUSTFILE
            value: /mnt/locust/locustfile.py
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
        - name: reports
          emptyDir: {}
